# Cosmos Discord Faucet configuration

verbose        = "yes"

[cosmos]
prefix         = "migaloo"
denomination   = "uwhale"

[testnets]
    [testnets.migaloo]
    node_url = "http://65.109.34.184:26657"
    chain_id = "narwhal-2"
    faucet_address = "migaloo1gc5pxlgp2392yjea7qqff9z8ka4lwdr8y4jjpg"
    block_explorer_tx = ""
    daily_cap = "50000000000"
    amount_to_send = "1000000"
    tx_fees = "500"

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "testnet-faucet"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "10800"