# Cosmos Discord Faucet configuration

verbose        = "yes"

[cosmos]
prefix         = "centauri"
denomination   = "ppica"

[testnets]
    [testnets.theta]
    node_url = "http://65.109.26.223:26657"
    chain_id = "banksy-testnet-5"
    faucet_address = "centauri10jx4vpu4uddyl7zvy24upy4kzkazxchk3nwqrf"
    block_explorer_tx = "https://explorer.stavr.tech/Composable-Testnet/tx/"
    daily_cap = "1000000000000000"
    amount_to_send = "10000000000ppica"
    tx_fees = "10000000"

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "faucet"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "86400"